title: Life of a nerdy guy
author: vstkl
subtitle: The life of a frustrated engineer

url: "https://vstkl.xyz"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://vstkl.xyz"
footer_text: "Theme borrowed with â™¡ from rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://vstkl.xyz/jekyll-cv"
